### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by jhurliman** [stevestreza/IIIAsync#4]
Looks like a podspec for this library has already been written by someone (https://gist.github.com/penman/10402517). Is it possible to add a podspec to the repository and submit this as a Cocoapod?

**Comment by jhurliman** [comment]
See PR #7

**Comment by stevestreza** [comment]
Podspec in the repo is ready to be pushed to Cocoapods trunk as of 84e415a, but needs @sdgandhi to transfer ownership of the `IIIAsync` pod namespace to me (or add me as an owner, or however you do this in Cocoapods land).

**Comment by sdgandhi** [comment]
@stevestreza Great, I'll add you. Is your email the one listed on your profile?

**Comment by stevestreza** [comment]
@sdgandhi steve at stevestreza dot com

**Comment by sdgandhi** [comment]
@stevestreza done, you can push to trunk now.

**Comment by stevestreza** [comment]
The updated podspec has been pushed to Cocoapods. Closing. Thanks for the help all! :)
